Repository JasperFx/marten, pull requests merged in 2019-12, with the labels that each got.

#1390 Fixes #1386 - not being able to serialize IReadonlyCollection<int> while using CollectionStorage.AsArray
  src/Marten.Testing/Documents/User.cs
  src/Marten.Testing/Linq/query_with_inner_query_with_global_CollectionStorage_WithArray.cs
  src/Marten.Testing/Session/document_session_load_document.cs
  src/Marten/Services/Json/JsonNetCollectionToArrayJsonConverter.cs
Labels: bug, serializer

#1403 Updated `publish-docs` to publish also to Netlify for Martendb.io domain
  martenbuild.cs
Labels: CI, Project Management, docs, enhancement

#1406 Fix mixed content and links in docs
  documentation/documentation/cli.md
  documentation/documentation/documents/configuration/unique.md
  documentation/documentation/postgres/naming.md
  documentation/documentation/postgres/types.md
  documentation/layout.htm
  documentation/splash.htm
Labels: docs
