Repository JasperFx/marten, pull requests merged in 2019-06, with the labels that each got.

#1267 Updated packages to most recent version. Added Benchmark project to s…
  azure-pipelines-benchmarks.yml
  src/Marten.NodaTime.Testing/Marten.NodaTime.Testing.csproj
  src/Marten.NodaTime/Marten.NodaTime.csproj
  src/Marten.Storyteller/Marten.Storyteller.csproj
  src/Marten.Testing.OtherAssembly/Marten.Testing.OtherAssembly.csproj
  src/Marten.Testing/Marten.Testing.csproj
  src/Marten.sln
  src/Marten/Marten.csproj
  src/MartenBenchmarks/BenchAgainst/UnitOfWorkBaseline.cs
  src/MartenBenchmarks/BulkLoading.cs
  src/MartenBenchmarks/DocumentActions.cs
  src/MartenBenchmarks/EventActions.cs
  src/MartenBenchmarks/LinqActions.cs
  src/MartenBenchmarks/MartenBenchmarks.csproj
  src/MartenBenchmarks/Program.cs
Labels: CI

#1279 Fixes concurrency bug on mt_append_event function when processing the same stream.
  src/Marten.Testing/Events/end_to_end_event_capture_and_fetching_the_stream_Tests.cs
  src/Marten/Events/AppendEventFunction.cs
  src/Marten/Events/EventGraph.cs
  src/Marten/Schema/SQL/mt_stream.sql
Labels: enhancement, event store

#1287 update SimpleExec to 6.0.0-beta.1
  martenbuild.cs
  martenbuild.csproj
Labels: CI, enhancement

#1285 Add unit test for retry policy.
  documentation/documentation/documents/advanced/retrypolicy.md
  src/Marten.Testing/Examples/RetryPolicyTests.cs
  src/Marten/IRetryPolicy.cs
Labels: docs, enhancement

#1289 Update docs
  documentation/documentation/documents/advanced/retrypolicy.md
  documentation/documentation/documents/diagnostics.md
  src/Marten.Testing/ability_to_fetch_postgres_server_version.cs
Labels: docs

#1298 Fix #1296. Return updates AND upserts in `IUnitOfWork.Updates` and `I…
  src/Marten.Testing/Bugs/Bug_1296_sessionlistener_updates.cs
  src/Marten/Services/UnitOfWork.cs
Labels: bug
