Repository JasperFx/marten, pull requests merged in 2019-03, with the labels that each got.

#1203 Would fix #1178:
  src/Marten.Testing/SessionOptionsTests.cs
  src/Marten/Linq/QueryPlan.cs
  src/Marten/Services/CommandRunnerExtensions.cs
  src/Marten/Services/ManagedConnection.cs
  src/Marten/Services/SessionOptions.cs
  src/Marten/Services/TransactionState.cs
  src/Marten/Storage/DefaultTenancy.cs
  src/Marten/Storage/ITenant.cs
  src/Marten/Storage/Tenant.cs
Labels: breaking change

#1213 Allow specifying index sort order for duplicated props (fixes #1199)
  src/Marten.Testing/Schema/IndexDefinitionTests.cs
  src/Marten.Testing/Schema/configuring_searchable_fields_Tests.cs
  src/Marten/Schema/DuplicateFieldAttribute.cs
  src/Marten/Schema/IndexDefinition.cs
  src/Marten/SortOrder.cs
Labels: enhancement

#1211 Expose IStorageOperations on IUnitOfWork
  src/Marten.Testing/UnitOfWork_PendingChanges_Functionality_Tests.cs
  src/Marten/Services/IUnitOfWork.cs
  src/Marten/Services/UnitOfWork.cs
Labels: enhancement

#1210 Reinstate previous function versions in patch rollback DDL
  src/Marten.Testing/Storage/UpsertFunctionTester.cs
  src/Marten/Storage/Function.cs
  src/Marten/Storage/FunctionDelta.cs
Labels: bug

#1208 Add scenario (docs) for copying & transforming event streams (for versioning…
  documentation/documentation/scenarios/copyandtransformstream.md
  src/Marten.Testing/ScenarioCopyAndReplaceStream.cs
Labels: docs
