Repository JasperFx/marten, pull requests merged in 2020-06, with the labels that each got.

#1496 Initial Data: Query in Populate method
  src/Marten.Testing/Bugs/Bug_1495_initial_data_populate_with_query_causing_null_ref_ex.cs
  src/Marten/DocumentStore.cs
Labels: Schema management, bug

#1426 Add support for IsOneOf to allow passing List<T> as opposed to arrays.
  documentation/documentation/documents/querying/linq.md
  src/Marten.Testing/Examples/IsOneOfArray.cs
  src/Marten.Testing/Examples/IsOneOfExamples.cs
  src/Marten.Testing/Linq/query_with_is_one_of_Tests.cs
  src/Marten/LinqExtensions.cs
Labels: enhancement, linq

#1497 Update package description in csproj files
  src/Marten.CommandLine/Marten.CommandLine.csproj
  src/Marten.NodaTime/Marten.NodaTime.csproj
  src/Marten/Marten.csproj
Labels: Project Management

#1498 Fix build tooling security vulnerability warning with npm package dependency
  package-lock.json
  package.json
Labels: build

#1456 Add possibility to start typed event streams with non-generic StartStream
  documentation/documentation/events/index.md
  src/Marten.Testing/Examples/event_store_quickstart.cs
  src/Marten/Events/EventStore.cs
  src/Marten/Events/IEventStore.cs
Labels: enhancement, event store

#1501 DI registrations
  documentation/documentation/integration.md
  documentation/documentation/order.txt
  documentation/getting_started.md
  src/AspNetCoreWithMarten/AspNetCoreWithMarten.csproj
  src/AspNetCoreWithMarten/IssueController.cs
  src/AspNetCoreWithMarten/Program.cs
  src/AspNetCoreWithMarten/Properties/launchSettings.json
  src/AspNetCoreWithMarten/Samples/ByConnectionString/Startup.cs
  src/AspNetCoreWithMarten/Samples/ByNestedClosure/Startup.cs
  src/AspNetCoreWithMarten/Samples/ByStoreOptions/Startup.cs
  src/AspNetCoreWithMarten/Samples/ConfiguringSessionCreation/Startup.cs
  src/AspNetCoreWithMarten/Samples/EagerInitialization/Startup.cs
  src/AspNetCoreWithMarten/Samples/PerScopeSessionCreation/Startup.cs
  src/AspNetCoreWithMarten/Startup.cs
  src/AspNetCoreWithMarten/appsettings.Development.json
  src/AspNetCoreWithMarten/appsettings.json
  src/Marten.Testing/DevelopmentModeRegistry.cs
  src/Marten.Testing/Marten.Testing.csproj
  src/Marten.Testing/MartenServiceCollectionExtensionsTests.cs
  src/Marten.Testing/MultiTenancy/with_batched_queries.cs
  src/Marten.Testing/MultiTenancy/with_optimistic_concurrency.cs
  src/Marten.sln
  src/Marten/Marten.csproj
  src/Marten/MartenServiceCollectionExtensions.cs
Labels: DI, enhancement

#1508 Call the correct TransactionState constructor
  src/Marten.Testing/CoreFunctionality/SessionOptionsTests.cs
  src/Marten/Services/ManagedConnection.cs
Labels: bug, connection mangement
