Repository JasperFx/marten, pull requests merged in 2020-08, with the labels that each got.

#1541 doc: Update link to latest postgres version
  documentation/documentation/postgres/types.md
Labels: docs

#1543 Introduce DefaultRetryPolicy
  documentation/documentation/documents/advanced/retrypolicy.md
  src/Marten.Testing/Examples/RetryPolicyTests.cs
  src/Marten.Testing/Services/DefaultRetryPolicyTests.cs
  src/Marten/IRetryPolicy.cs
Labels: enhancement

#1542 Support case-insensitive order by for strings
  src/Marten.Testing/Examples/LinqExamples.cs
  src/Marten.Testing/Linq/Compatibility/simple_order_by_clauses.cs
  src/Marten/Linq/MartenQueryParser.cs
  src/Marten/Linq/Model/LinqQuery.cs
  src/Marten/Linq/Model/SelectManyQuery.cs
  src/Marten/Linq/OrderByComparerClause.cs
  src/Marten/Linq/OrderByComparerExpressionNode.cs
  src/Marten/Linq/OrderByComparerOperator.cs
  src/Marten/Linq/OrderByOperator.cs
  src/Marten/Util/OrderingExtensions.cs
Labels: enhancement, linq

#1549 Fix enum reflection for .NET 5
  src/Marten/Util/LambdaBuilder.cs
Labels: .NET 5, bug
