Repository JasperFx/marten, pull requests merged in 2020-12, with the labels that each got.

#1633 add IAsyncDisposable support
  src/Marten/Events/Projections/Async/Daemon.cs
  src/Marten/Events/Projections/Async/Fetcher.cs
  src/Marten/Events/Projections/Async/ProjectionTrack.cs
  src/Marten/IQuerySession.cs
  src/Marten/Internal/IMartenSession.cs
  src/Marten/Internal/Sessions/QuerySession.cs
  src/Marten/Services/IManagedConnection.cs
  src/Marten/Services/ManagedConnection.cs
  src/Marten/Services/TransactionState.cs
Labels: connection mangement, enhancement

#1632 remove some duplicate dictionary lookups
  src/Marten/Events/Projections/Aggregator.cs
  src/Marten/Events/Projections/Async/Daemon.cs
  src/Marten/Internal/Storage/IdentityMapDocumentStorage.cs
  src/Marten/Patching/PatchOperation.cs
  src/Marten/Services/VersionTracker.cs
  src/Marten/Storage/StorageFeatures.cs
  src/Marten/Storage/TableDelta.cs
  src/Marten/Transforms/ITransforms.cs
Labels: performance

#1675 Fix for using wrong overload in GinIndexedAttribute and test
  src/Marten.Schema.Testing/DocumentMappingTests.cs
  src/Marten/Schema/GinIndexedAttribute.cs
Labels: 4.x, bug, indexes

#1667 use c# discards
  src/Marten/Events/Projections/Async/Fetcher.cs
  src/Marten/Events/Projections/ViewProjection.cs
  src/Marten/Events/V4Concept/CodeGeneration/EventDocumentStorageGenerator.cs
  src/Marten/Linq/Fields/FieldCollection.cs
  src/Marten/Schema/ForeignKeyDefinition.cs
  src/Marten/Storage/Tenant.cs
  src/Marten/StoreOptions.cs
  src/Marten/Transforms/TransformFunction.cs
Labels: .NET, 4.x, enhancement
