Repository JasperFx/marten, pull requests merged in 2020-02, with the labels that each got.

#1423 Document additional plv8 options for newer versions of PostgreSQL.
  documentation/documentation/admin/installing-plv8-windows.md
Labels: docs

#1420 Fix ComputedIndex DDL generation when non-default casing is present
  src/Marten.Testing/Acceptance/computed_indexes.cs
  src/Marten/Schema/ComputedIndex.cs
Labels: Schema management, bug

#1410 Make DeleteAllEventData safe for empty database.
  src/Marten/Schema/DocumentCleaner.cs
Labels: bug, event store
