Repository JasperFx/marten, pull requests merged in 2020-11, with the labels that each got.

#1580 Added Static ID for initial data Documentation
  src/Marten.Testing/Bugs/Bug_962_initial_data_populate_causing_null_ref_ex.cs
  src/Marten.Testing/Documents/Company.cs
Labels: bug, docs

#1566 Remove incorrect comment
  src/Marten.Testing/Examples/event_store_quickstart.cs
Labels: bug, docs

#1592 Remove NET461 leftovers and multi-target net5
  .github/workflows/on-manual-do-nuget-publish.yml
  README.md
  documentation/getting_started.md
  martenbuild.cs
  src/Marten.CommandLine.Testing/Marten.CommandLine.Testing.csproj
  src/Marten.CommandLine/Marten.CommandLine.csproj
  src/Marten.NodaTime.Testing/Marten.NodaTime.Testing.csproj
  src/Marten.NodaTime/Marten.NodaTime.csproj
  src/Marten.Schema.Testing/IntegrationContext.cs
  src/Marten.Schema.Testing/Marten.Schema.Testing.csproj
  src/Marten.Storyteller/Marten.Storyteller.csproj
  src/Marten.Testing.OtherAssembly/Marten.Testing.OtherAssembly.csproj
  src/Marten.Testing/Acceptance/document_inserts.cs
  src/Marten.Testing/Acceptance/fetching_entity_metadata.cs
  src/Marten.Testing/Acceptance/projecting_metadata_to_documents.cs
  src/Marten.Testing/Bugs/Bug_949_connection_closing_issue_with_transaction_scope.cs
  src/Marten.Testing/CoreFunctionality/ability_to_use_an_existing_connection_and_transaction.cs
  src/Marten.Testing/Harness/StoreContext.cs
  src/Marten.Testing/Marten.Testing.csproj
  src/Marten.Testing/Util/LambdaBuilderTester.cs
  src/Marten.Testing/performance_tuning.cs
  src/Marten/Events/Projections/Async/ProjectionTrack.cs
  src/Marten/Linq/Parsing/Methods/StringEndsWith.cs
  src/Marten/Linq/Parsing/StringStartsWith.cs
  src/Marten/Marten.csproj
  src/Marten/Util/LambdaBuilder.cs
  src/MartenBenchmarks/MartenBenchmarks.csproj
  src/StorytellerRunner/StorytellerRunner.csproj
Labels: .NET 5, CI, dependencies

#1597 Add limit 0 to create a temp table with schema only
  src/Marten/Schema/BulkLoading/BulkLoader.cs
Labels: bug

#1588 Sorting Problem
  src/Marten.Testing/CoreFunctionality/document_session_sort_large_operation_bundle_Tests.cs
  src/Marten/Internal/UnitOfWork.cs
Labels: bug, linq

#1605 Remove type mappers from nodatime implementation on 3.x
  src/Marten.NodaTime/Marten.NodaTime.csproj
  src/Marten.NodaTime/NodaTimeExtensions.cs
  src/Marten/Events/EventQueryHandler.cs
  src/Marten/Events/EventSelector.cs
  src/Marten/Events/StreamStateByGuidHandler.cs
  src/Marten/Events/StringIdentifiedEventSelector.cs
  src/Marten/Marten.csproj
  src/Marten/Storage/EntityMetadataQueryHandler.cs
  src/Marten/Util/TypeMappings.cs
Labels: NodaTime, enhancement

#1607 Sorting problem with one operation being delete on 3.x
  src/Marten.Testing/CoreFunctionality/document_session_sort_large_operation_bundle_Tests.cs
  src/Marten/Services/UnitOfWork.cs
Labels: bug, linq
