Repository JasperFx/marten, pull requests merged in 2020-07, with the labels that each got.

#1518 Fix a compatibility issue with .NET 5
  src/Marten/Marten.csproj
Labels: .NET

#1520 Fix duplicate field schema generation to respect casing
  src/Marten.Schema.Testing/DuplicatedFieldTests.cs
  src/Marten/Schema/DuplicatedField.cs
Labels: bug, schema management

#1538 Update computed_indexes.cs sample
  src/Marten.Testing/Acceptance/computed_indexes.cs
Labels: docs, multi-tenancy

#1531 Update min. version of npgsql and npgsql.* libs to 4.1.4 - closes #1529
  src/Marten.NodaTime/Marten.NodaTime.csproj
  src/Marten/Marten.csproj
Labels: dependencies

#1530 Update js dev build dependencies
  package-lock.json
  package.json
Labels: CI, javascript
