Repository JasperFx/marten, pull requests merged in 2022-01, with the labels that each got.

#2033 Xtuple binary download link is broken
  docs/documents/plv8.md
Labels: docs

#2016 Treat the Identity Field as a Duplicated Field
  src/Marten.Testing/Linq/Bug_id_field_does_not_hit_id_column.cs
  src/Marten/Linq/Parsing/SimpleBinaryComparisonExpressionParser.cs
  src/Marten/Linq/Parsing/SimpleEqualsParser.cs
Labels: 3.x

#2050 (docs) Fix tiny typo
  documentation/documentation/admin/installing-plv8-windows.md
Labels: bug, docs, 5.x
