Repository JasperFx/marten, pull requests merged in 2022-12, with the labels that each got.

#2416 Fixed issue for the NonPublicMembersStorage.All serializer resolution causing Record with a single parameter fail to deserialize
  docs/documents/identity.md
  src/EventSourcingTests/Json/JsonSerializationTests.cs
  src/Marten/Services/Json/JsonNetObjectContractProvider.cs
Labels: bug, serializer, 6.x

#2406 Fixed xml doc comments for ProjectionOptions
  src/Marten/Events/Projections/ProjectionOptions.cs
Labels: bug, docs, 6.x

#2423 Added note to docs about parameter casting
  docs/documents/execute-custom-sql.md
  src/CoreTests/executing_arbitrary_sql_as_part_of_transaction.cs
Labels: docs

#2434 Fix GH-2398
  src/DocumentDbTests/Indexes/NgramSearchTests.cs
  src/DocumentDbTests/Reading/Linq/SoftDeletes/DeletedBeforeParserTests.cs
  src/DocumentDbTests/Reading/Linq/SoftDeletes/DeletedSinceParserTests.cs
  src/DocumentDbTests/Reading/Linq/using_custom_Linq_parser_plugins_Tests.cs
  src/Marten/Events/Archiving/MaybeArchivedMethodCallParser.cs
  src/Marten/Linq/LastModified/ModifiedBeforeParser.cs
  src/Marten/Linq/LastModified/ModifiedSinceParser.cs
  src/Marten/Linq/MatchesSql/MatchesSqlParser.cs
  src/Marten/Linq/Parsing/DictionaryExpressions.cs
  src/Marten/Linq/Parsing/EnumerableContains.cs
  src/Marten/Linq/Parsing/IMethodCallParser.cs
  src/Marten/Linq/Parsing/MethodCallParser.cs
  src/Marten/Linq/Parsing/Methods/AnyTenant.cs
  src/Marten/Linq/Parsing/Methods/EqualsIgnoreCaseParser.cs
  src/Marten/Linq/Parsing/Methods/FullTextSearchMethodCallParser.cs
  src/Marten/Linq/Parsing/Methods/IsEmpty.cs
  src/Marten/Linq/Parsing/Methods/IsInGenericEnumerable.cs
  src/Marten/Linq/Parsing/Methods/IsNotOneOf.cs
  src/Marten/Linq/Parsing/Methods/IsOneOf.cs
  src/Marten/Linq/Parsing/Methods/IsSubsetOf.cs
  src/Marten/Linq/Parsing/Methods/IsSupersetOf.cs
  src/Marten/Linq/Parsing/Methods/NgramSearch.cs
  src/Marten/Linq/Parsing/Methods/SimpleEqualsParser.cs
  src/Marten/Linq/Parsing/Methods/StringComparisonParser.cs
  src/Marten/Linq/Parsing/Methods/TenantIsOneOf.cs
  src/Marten/Linq/Parsing/WhereClauseParser.cs
  src/Marten/Linq/SoftDeletes/DeletedBeforeParser.cs
  src/Marten/Linq/SoftDeletes/DeletedSinceParser.cs
  src/Marten/Linq/SoftDeletes/IsDeletedParser.cs
  src/Marten/Linq/SoftDeletes/MaybeDeletedParser.cs
  src/Marten/LinqParsing.cs
  src/Marten/Schema/SQL/mt_grams_query.sql
  src/Marten/Schema/SQL/mt_grams_vector.sql
Labels: breaking change

#2431 Fix a compatibility issue with .NET 7 and Marten 3.x
  src/Marten/Marten.csproj
Labels: 3.x
